# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python



jobs:

- job: 'codecov'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
  variables:
    OMP_NUM_THREADS: '2'
    NUMBA_NUM_THREADS: '2'
    PIP_PREFER_BINARY: 'true'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      set -xe
      python --version
      python -m pip install --upgrade pip
      python -m pip install .[tests,all_features]
    displayName: 'Install tslearn all_features and dependencies for tests'

  - script: |
      set -xe
      python -m pip install pytest-azurepipelines
      python -m pip install coverage pytest-cov
      pip list
      python -m pytest -v tslearn/ --cov=tslearn --doctest-modules
    displayName: 'Test'

  # Upload coverage to codecov.io
  - script: |
      set -xe
      pip install codecov-cli
      codecovcli --verbose upload-process --disable-search -f coverage.xml
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN_SECRET)
    displayName: 'Upload coverage to codecov.io'

  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'sonarqube_inria'
      scannermode: 'cli'
    displayName: 'Prepare analysis'
  - task: SonarQubeAnalyze@7
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
    displayName: 'Run analysis'
    env:
      SONAR_TOKEN: $(SONARQUBE_TOKEN_SECRET)
