# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- test_macos

jobs:
- job: 'doctests_linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'
  variables:
    KERAS_BACKEND: 'torch'
    OMP_NUM_THREADS: '2'
    NUMBA_NUM_THREADS: '2'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      set -xe
      python --version
      python -m pip install --upgrade pip
      python -m pip install -e '.[tests,all_features]'
    displayName: 'Install tslearn and dependencies for tests'

  - script: |
      set -xe
      python -m pip install pytest-azurepipelines
      pip list
      python -m pytest -v tslearn/ --doctest-modules -k "not test_ or test_all_estimators"
    displayName: 'Doctest'

- job: 'tests_macOS'
  pool:
    vmImage: 'macos-latest'
  strategy:
    matrix:
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'

  variables:
    KERAS_BACKEND: 'torch'
    OMP_NUM_THREADS: '2'
    NUMBA_NUM_THREADS: '2'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      set -xe
      python --version
      brew install openblas  # required due to https://github.com/numpy/numpy/issues/15947
      export OPENBLAS=$(brew --prefix openblas)
      python -m pip install --upgrade pip
      python -m pip install -e '.[tests,all_features]'
    displayName: 'Install tslearn and dependencies for tests'

  - script: |
      set -xe
      python -m pip install pytest-azurepipelines
      pip list
      python -m pytest -v tslearn/ -k "not test_all_estimators"
    displayName: 'Test'

- job: 'doctests_macOS'
  pool:
    vmImage: 'macos-latest'
  strategy:
    matrix:
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'

  variables:
    KERAS_BACKEND: 'torch'
    OMP_NUM_THREADS: '2'
    NUMBA_NUM_THREADS: '2'
    PIP_PREFER_BINARY: 'true'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      set -xe
      python --version
      brew install openblas  # required due to https://github.com/numpy/numpy/issues/15947
      export OPENBLAS=$(brew --prefix openblas)
      python -m pip install --upgrade pip
      python -m pip install -e '.[tests,all_features]'
    displayName: 'Install tslearn and dependencies for tests'

  - script: |
      set -xe
      python -m pip install pytest-azurepipelines
      pip list
      python -m pytest -v tslearn/ --doctest-modules -k "not test_ or test_all_estimators"
    displayName: 'Doctest'
