# -*- coding: utf-8 -*-
#
# tslearn documentation build configuration file, created by
# sphinx-quickstart on Mon May  8 21:34:49 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import subprocess
import sys
import tomllib
import warnings

from packaging.requirements import Requirement

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
on_rtd = os.environ.get('READTHEDOCS') == 'True'
if not on_rtd:
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
rtd_version = os.environ.get('READTHEDOCS_VERSION', 'local')

import tslearn


# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.mathjax',
    'sphinx.ext.intersphinx',
    'sphinx.ext.linkcode',
    'sphinx_gallery.gen_gallery',
    'sphinx_copybutton',
    'numpydoc'
]

numpydoc_show_class_members = True
numpydoc_class_members_toctree = False

autosummary_generate = True
autosummary_generate_overwrite = False

intersphinx_mapping = {
    'python': ('https://docs.python.org/{.major}'.format(
        sys.version_info), None),
    'numpy': ('https://numpy.org/doc/stable', None),
    'scipy': ('https://docs.scipy.org/doc/scipy', None),
    'matplotlib': ('https://matplotlib.org/stable', None),
    'sklearn': ('https://scikit-learn.org/stable', None)
}

from sphinx_gallery.scrapers import matplotlib_scraper

def matplotlib_svg_scraper(*args, **kwargs):
    """ SVG scrapper """
    kwargs.pop("format", None)
    return matplotlib_scraper(*args, format='svg', **kwargs)

sphinx_gallery_conf = {
    'examples_dirs': ['./examples'],
    'gallery_dirs': ['./auto_examples'],
    'reference_url': {'tslearn': None},
    'default_thumb_file': os.path.join(os.path.dirname(__file__),
                                       '_static/img/logo.png'),
    'backreferences_dir': 'gen_modules/backreferences',
    'doc_module': ('tslearn',),
    'subsection_order': ["examples/metrics", "examples/neighbors",
                         "examples/clustering", "examples/classification",
                         "examples/autodiff", "examples/misc"].index,
    'within_subsection_order': "FileNameSortKey",
    'image_scrapers': (matplotlib_svg_scraper,),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'tslearn'
copyright = u'2025, Romain Tavenard'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
version = tslearn.__version__
# The full version, including alpha/beta/rc tags.
release = tslearn.__version__

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build",
    "**sg_execution_times**",
    "examples/**/*.py",
    "auto_examples/**/*.ipynb",
    "auto_examples/**/*.py"
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = 'sphinx_rtd_theme'
html_theme = 'pydata_sphinx_theme'
html_theme_options = {

    "github_url": "https://github.com/tslearn-team/tslearn",
    "navbar_align": "left",
    "primary_sidebar_end": [],
    "secondary_sidebar_items": [],
    "show_version_warning_banner": True,

}

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/tslearn_logo_white_background.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/tslearn_logo.svg"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['custom.css']

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    "auto_examples/*": [],
    "citing": []
}

# Output file base name for HTML help builder.
htmlhelp_basename = 'tslearndoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'tslearn.tex', u'tslearn Documentation',
   u'Romain Tavenard', 'manual'),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'tslearn', u'tslearn Documentation',
     [u'Romain Tavenard'], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'tslearn', u'tslearn Documentation',
   u'Romain Tavenard', 'tslearn', 'One line description of project.',
   'Miscellaneous'),
]

# The following is used by sphinx.ext.linkcode to provide links to github
REVISION_CMD = 'git rev-parse --short HEAD'


def _get_git_revision():
    try:
        revision = subprocess.check_output(REVISION_CMD.split()).strip()
    except (subprocess.CalledProcessError, OSError):
        print('Failed to execute git to get revision')
        return None
    return revision.decode('utf-8')

def linkcode_resolve(domain, info):
    def find_source():
        # try to find the file and line number, based on code from numpy:
        # https://github.com/numpy/numpy/blob/master/doc/source/conf.py#L286
        obj = sys.modules[info['module']]
        for part in info['fullname'].split('.'):
            obj = getattr(obj, part)
        import inspect
        import os
        if hasattr(obj, "__wrapped__"):
            obj = obj.__wrapped__
        if not obj.__module__.startswith('tslearn'):
            raise RuntimeError('Not a tslearn module')
        fn = inspect.getsourcefile(obj)
        fn = os.path.relpath(fn, start=os.path.dirname(tslearn.__file__))
        source, lineno = inspect.getsourcelines(obj)
        return fn, lineno, lineno + len(source) - 1

    if domain != 'py' or not info['module']:
        return None
    try:
        filename = 'tslearn/%s#L%d-L%d' % find_source()
    except RuntimeError:
        return None
    except Exception:
        filename = info['module'].replace('.', '/') + '.py'
    revision = _get_git_revision()
    return "https://github.com/tslearn-team/tslearn/blob/%s/%s" % (revision,
                                                                   filename)


warnings.filterwarnings("ignore", category=UserWarning,
                        message='Matplotlib is currently using agg, which is a'
                                ' non-GUI backend, so cannot show the figure.')


def get_dependencies():
    """ Retrieve required dependencies """
    with open("../pyproject.toml", "rb") as f:
        pyproject = tomllib.load(f)
        return [Requirement(requirement) for requirement in pyproject["project"]["dependencies"]]


rst_templates= {
    "dependencies.rst": {"dependencies": get_dependencies()}
}


def setup(app):
    """ Setup our app """
    # Ensure pandoc is installed
    import pypandoc
    pypandoc.ensure_pandoc_installed(
        targetfolder=os.path.join(sys.exec_prefix, "bin"),
        delete_installer=True,
    )

    # Deals with dynamic rst templates
    import jinja2
    config_value = 'rst_templates'
    def render_on_include_read(app_, relative_path, _, content):
        """
        Render our page as a jinja template with dedicated context
        on include-read event.
        """
        templates = getattr(app_.config, config_value, {})
        if str(relative_path) in templates:
            content[0] = jinja2.Template(content[0]).render(
                **templates[str(relative_path)]
            )
    def render_on_source_read(app_, doc_name, source):
        """
        Render our page as a jinja template with dedicated context
        on source-read event.
        """
        templates = getattr(app_.config, config_value, {})
        if doc_name + '.rst' in templates:
            rendered = jinja2.Template(source[0]).render(
                **templates[doc_name + '.rst']
            )
            source[0] = rendered
    app.add_config_value(config_value, {}, True, dict)
    app.connect("source-read", render_on_source_read)
    app.connect("include-read", render_on_include_read)
